### ISSUE TITLE
Add the zoom controls again

### ISSUE THREAD

**Issue by passsy** [robiness/stage_craft#35]
I always used the zoom controls, especially for tiny widgets and icons.

1x, 2x, 8x would be awesome!

**Comment by robiness** [comment]
Came up with a decent mousewheel zoom i think.
When having hardcoded values, its not to easy to position the child correctly.
Let me know where to improve and if those controls are still necessary.

**Comment by passsy** [comment]
Works great, but I still think static buttons would be helpful. Also a indicator how far I zoomed in with the mouse wheel
