### ISSUE TITLE
Force size by default

### ISSUE THREAD

**Issue by passsy** [robiness/stage_craft#36]
Stagecraft should automatically force the size of the widget, so that I can use the size controls to force a new size. I could see that it always works,

```dart
  @override
  Widget build(BuildContext context) {
    return StageBuilder(
      builder: (context) {
        return SizedBox(              // <-- should be added 
          width: double.infinity,     // <-- automatically
          height: double.infinity,    // <-- by stagecraft
          child: PillButton(
            onTap: _hasFunction.value ? () {} : null,
            label: _label.value,
            enabled: _enabled.value,
          ),
        );
      },
      controls: [
        _hasFunction,
        _label,
        _enabled,
      ],
    );
  }
}
```

I used this setup with `double.infinity` as a workaround. But now that stagecraft uses the intrinsic width/height it doesn't work anymore. I'd like to have it as a default option.

### Without forced size
![Screen-Shot-2024-07-10-15-20-15 78](https://github.com/robiness/stage_craft/assets/1096485/a116cb68-32db-446b-ac1a-c46904d4afe5)

### With forced size
![Screen-Shot-2024-07-10-15-19-42 87](https://github.com/robiness/stage_craft/assets/1096485/90449c36-8c91-42ce-bf63-a0230b0e16af)

**Comment by robiness** [comment]
Do you expect a `forceSize` which defaults to `true` on `StageBuilder`?

**Comment by passsy** [comment]
Yes, `forceSize` should default to true.

Maybe add a button "[ ] intrinsic width/height" that allows me to explicitly test the intrinsic size
