### ISSUE TITLE
Hide box around widget

### ISSUE THREAD

**Issue by passsy** [robiness/stage_craft#37]
![Screen-Shot-2024-07-10-15-21-15 15](https://github.com/robiness/stage_craft/assets/1096485/955affff-79c6-4803-969d-18a9bded7569)

It is hard to see the shadow around my button because of the square box.

I'd like to hide it sometimes in the user interface

**Comment by robiness** [comment]
It's now coupled to the ruler visibility:
| rulers visible | rulers not visible |
|--------|-------|
|   <img width="387" alt="image" src="https://github.com/robiness/stage_craft/assets/34774539/6b2d9dae-e5e2-486b-8838-96a80e22d9bd">|     
<img width="306" alt="image" src="https://github.com/robiness/stage_craft/assets/34774539/b3876a0a-03b0-4d29-aaf2-560210e9ff73">|

Let me know if that makes sense
